# Generated by Django 4.0.2 on 2022-02-14 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=150)),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='main_app.architect')),
            ],
        ),
    ]
